# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
url: http://govindrajann.github.io
baseurl:          ""

# Site Settings
title: Govind rajan - Profile  
description: "Professional Timeline."
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]

plugins:
  - jekyll-gist
  - jekyll-paginate